arm_left_impedance_controller:
  type: "impedance_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  robot_model_chains: ["gripper_left_link"]
  impedance_gains:
    arm_left_1_joint: {kp: -6.0, kd: -1.0}
    arm_left_2_joint: {kp: -6.0, kd: -0.8}
    arm_left_3_joint: {kp: 6.0, kd: 0.8}
    arm_left_4_joint: {kp: 6.0, kd: 0.8}
    arm_left_5_joint: {kp: 0.02, kd: 0.02}
    arm_left_6_joint: {kp: 0.2, kd: 0.02}
    arm_left_7_joint: {kp: 0.25, kd: 0.2}
  motor_params:
    arm_left_1_joint: {motor_torque_constant: 0.0, reduction_ratio: 100.0}
    arm_left_2_joint: {motor_torque_constant: 0.136, reduction_ratio: -100.0}
    arm_left_3_joint: {motor_torque_constant: -0.087, reduction_ratio: -100.0}
    arm_left_4_joint: {motor_torque_constant: -0.087, reduction_ratio: -100.0}
    arm_left_5_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_left_6_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_left_7_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_left_1_joint:
      goal: 0.02
    arm_left_2_joint:
      goal: 0.02
    arm_left_3_joint:
      goal: 0.02
    arm_left_4_joint:
      goal: 0.02
    arm_left_5_joint:
      goal: 0.02
    arm_left_6_joint:
      goal: 0.02
    arm_left_7_joint:
      goal: 0.02

arm_right_impedance_controller:
  type: "impedance_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  robot_model_chains: ["gripper_right_link"]
  impedance_gains:
    arm_right_1_joint: {kp: 6.0, kd: 1.0}
    arm_right_2_joint: {kp: 6.0, kd: 0.8}
    arm_right_3_joint: {kp: -6.0, kd: -0.8}
    arm_right_4_joint: {kp: -6.0, kd: -0.8}
    arm_right_5_joint: {kp: -0.02, kd: -0.02}
    arm_right_6_joint: {kp: 0.2, kd: 0.02}
    arm_right_7_joint: {kp: 0.2, kd: 0.2}
  motor_params:
    arm_right_1_joint: {motor_torque_constant: 0.0, reduction_ratio: 100.0}
    arm_right_2_joint: {motor_torque_constant: 0.136, reduction_ratio: 100.0}
    arm_right_3_joint: {motor_torque_constant: -0.087, reduction_ratio: 100.0}
    arm_right_4_joint: {motor_torque_constant: -0.087, reduction_ratio: 100.0}
    arm_right_5_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_right_6_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_right_7_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_right_1_joint:
      goal: 0.02
    arm_right_2_joint:
      goal: 0.02
    arm_right_3_joint:
      goal: 0.02
    arm_right_4_joint:
      goal: 0.02
    arm_right_5_joint:
      goal: 0.02
    arm_right_6_joint:
      goal: 0.02
    arm_right_7_joint:
      goal: 0.02
