arm_left_impedance_controller:
  motor_params:
    arm_left_1_joint: {motor_torque_constant: 0.0, reduction_ratio: 100.0}
    arm_left_2_joint: {motor_torque_constant: 0.136, reduction_ratio: -100.0}
    arm_left_3_joint: {motor_torque_constant: -0.087, reduction_ratio: -100.0}
    arm_left_4_joint: {motor_torque_constant: -0.087, reduction_ratio: -100.0}
    arm_left_5_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_left_6_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_left_7_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
