arm_right_impedance_controller:
  motor_params:
    arm_right_1_joint: {motor_torque_constant: 0.0, reduction_ratio: 100.0}
    arm_right_2_joint: {motor_torque_constant: 0.136, reduction_ratio: 100.0}
    arm_right_3_joint: {motor_torque_constant: -0.087, reduction_ratio: 100.0}
    arm_right_4_joint: {motor_torque_constant: -0.087, reduction_ratio: 100.0}
    arm_right_5_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_right_6_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}
    arm_right_7_joint: {motor_torque_constant: 0.0, reduction_ratio: 336.0}