play_motion2:
  ros__parameters:
    motions:
      home:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [-1.1, -0.48, 2.714, 1.7095, -1.2012, 1.3898, 0.0, 0.25,
                    -1.1, 1.4679, 2.714, 1.7095, -1.2012, 1.3898, 0.0, 0.25,
                    -1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0.0, 0.15]
        times_from_start: [0.0, 3.0, 4.5]
        meta:
          name: Home
          usage: demo
          description: Go home
      home_right:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [-1.1, -0.48, 2.714, 1.7095, -1.2012, 1.3898, 0.0, 0.25,
                    -1.1, 1.4679, 2.714, 1.7095, -1.2012, 1.3898, 0.0, 0.25,
                    -1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0.0, 0.15]
        times_from_start: [0.0, 3.0, 4.5]
        meta:
          name: Home Right
          usage: demo
          description: Go home, only right arm
      unfold_arm_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        positions: [0.30, 0.21, -0.74, 2.71, 1.03, -1.57, 1.37, 0.0,
                    0.30, 0.21, -0.2, 0.61, 1.15, -1.57, 0.2, 0.0]
        times_from_start: [0.5, 6.0]
        meta:
          name: Unfold arm right
          usage: demo
          description: Unfold right arm
      wave:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [-1.1, 1.4679, 1.2, 1.9348, -1.571, 1.0, -1.61, 0.15,
                    -0.0002, 1.0, 0.0, 1.7, -1.5699, 0.5, -1.61, 0.15,
                    0.0, 0.5, -0.0002, 2.2105, -1.5698, 0.3, -1.61, 0.15,
                    0.0, 0.6, -0.0002, 1.7, -1.5698, -0.3, -1.61, 0.15,
                    0.0, 0.5, -0.0002, 2.2869, -1.5698, 0.3, -1.61, 0.15,
                    0.0, 0.6, -0.0002, 1.7, -1.5698, -0.3, -1.61, 0.15,
                    0.0, 0.5, -0.0002, 2.2869, -1.5698, 0.3, -1.61, 0.15,
                    -1.1, 1.4679, 1.2, 1.9348, -1.571, 1.0, -1.61, 0.15,
                    -1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0.0, 0.15]
        times_from_start: [0.0, 2.0, 3.2, 4.4, 5.6, 6.8, 8.0, 10.0, 12.5]
        meta:
          name: Wave
          usage: enternainment
          description: Wave to the crowd
      offer:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [1.5, 0.5776, 0.0601, 1.0064, -1.7003, 0.0, 0.0, 0.15]
        times_from_start: [0.0]
        meta:
          name: Offer
          usage: demo
          description: Offer hand
      reach_floor:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [0.1703, 1.4609, 1.3424, 1.7078, -1.7005, 1.3899, 0.0, 0.15,
                    -0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.15,
                    -0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.12]
        times_from_start: [0.0, 2.5, 4.0]
        meta:
          name: Reach Floor Right
          usage: demo
          description: Reach floor
      reach_max:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [0.5093, -0.3532, 1.0323, 1.2011, -1.6999, 0.0306, 0.0, 0.23,
                    0.9008, -1.08, 1.1101, 0.2261, -1.7002, 0.6149, 0.0, 0.35]
        times_from_start: [0.0, 2.5]
        meta:
          name: Reach Max Right
          usage: demo
          description: Reach max
      vertical_reach:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [0.1703, 1.4609, 1.3424, 1.7078, -1.7005, 0.6945, 0.0, 0.15,
                    -0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.35,
                    -0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.35,
                    -0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.155]
        times_from_start: [0.0, 2.5, 3.0, 5.5]
        meta:
          name: Vertical Reach
          usage: demo
          description: Reach Max and Min
      horizontal_reach:
        joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, torso_lift_joint]
        positions: [-0.5, 1.0028, 1.5016, 1.9978, -1.6999, -0.0015, 0.0, 0.2,
                    0.0, 0.0094, 1.4999, 0.0009, -1.6999, 0.0003, 0.0001, 0.25]
        times_from_start: [0.0, 3.0]
        meta:
          name: Horizontal Reach
          usage: demo
          description: Reach Left and Right
