play_motion:
  motions:
    home:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, -0.48, 2.714, 1.7095, -1.2012, 1.3898, 0, 0.25]
        - time_from_start: 3
          positions: [-1.1, 1.4679, 2.714, 1.7095, -1.2012, 1.3898, 0, 0.25]
        - time_from_start: 4.5
          positions: [-1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0, 0.15]
      meta:
        name: Home
        usage: demo
        description: Go home
    home_left:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, -0.48, 2.714, 1.7095, -1.2012, 1.3898, 0, 0.25]
        - time_from_start: 3
          positions: [-1.1, 1.4679, 2.714, 1.7095, -1.2012, 1.3898, 0, 0.25]
        - time_from_start: 4.5
          positions: [-1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0, 0.15]
      meta:
        name: Home Left
        usage: demo
        description: Go home, only left arm
    wave:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, 1.4679, 2.714, 1.9347, -1.5703, 1.3699, 0.0008, 0.15]
        - time_from_start: 2
          positions: [-1.1, 1.4668, 2.714, 1.9331, -1.5703, 1.3698, 0.0009, 0.15]
        - time_from_start: 3.2
          positions: [-1.1, 1.4658, 2.714, 1.9315, -1.5703, 1.3698, 0.0009, 0.15]
        - time_from_start: 4.4
          positions: [-1.1, 1.4648, 2.714, 1.9299, -1.5703, 1.3698, 0.0009, 0.15]
        - time_from_start: 5.6
          positions: [-1.0999, 1.4637, 2.714, 1.9282, -1.5702, 1.3698, 0.001, 0.15]
        - time_from_start: 6.8
          positions: [-1.1, 1.4648, 2.714, 1.9299, -1.5703, 1.3698, 0.0009, 0.15]
        - time_from_start: 8
          positions: [-1.0999, 1.4637, 2.714, 1.9282, -1.5702, 1.3698, 0.001, 0.15]
        - time_from_start: 10
          positions: [-1.1, 1.4679, 2.714, 1.9347, -1.5703, 1.3699, 0.0008, 0.15]
        - time_from_start: 12.5
          positions: [-1.1, 1.4679, 2.714, 1.7095, -1.5708, 1.3898, 0, 0.15]
      meta:
        name: Wave
        usage: enternainment
        description: Wave to the crowd
    offer:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [1.5, 0.5776, 0.0601, 1.0064, -1.7003, 0, 0, 0.15]
      meta:
        name: Offer
        usage: demo
        description: Offer hand
    reach_floor:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [0.1703, 1.4609, 1.3424, 1.7078, -1.7005, 1.3899, 0, 0.15]
        - time_from_start: 2.5
          positions: [-0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.15]
        - time_from_start: 4
          positions: [-0.06, 1.16, 2.17, 0.75, -0.95, 0.47, -0.04, 0.12]
      meta:
        name: Reach Floor
        usage: demo
        description: Reach floor
    reach_max:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [0.5093, -0.3532, 1.0323, 1.2011, -1.6999, 0.0306, 0, 0.23]
        - time_from_start: 2.5
          positions: [0.9008, -1.08, 1.1101, 0.2261, -1.7002, 0.6149, 0, 0.35]
      meta:
        name: Reach Max
        usage: demo
        description: Reach max
    vertical_reach:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [0.5093, -0.3532, 1.0323, 1.2011, -1.6999, 0.0306, 0, 0.15]
        - time_from_start: 2.5
          positions: [0.9008, -1.08, 1.1101, 0.2261, -1.7002, 0.6149, 0, 0.35]
        - time_from_start: 3
          positions: [0.9008, -1.08, 1.1101, 0.2261, -1.7002, 0.6149, 0, 0.35]
        - time_from_start: 5.5
          positions: [0.9008, -1.08, 1.1101, 0.2261, -1.7002, 0.6149, 0, 0.155]
      meta:
        name: Vertical Reach
        usage: demo
        description: Reach Max and Min
    horizontal_reach:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-0.5, 1.0027, 1.5016, 1.9977, -1.6999, -0.0018, 0, 0.2]
        - time_from_start: 3
          positions: [0, 0.0093, 1.4999, -0.0001, -1.6999, 0.0002, 0.0001, 0.25]
      meta:
        name: Horizontal Reach
        usage: demo
        description: Reach Left and Right

# Alive motions
    alive_1:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, 1.4636, 2.7142, 1.7041, -1.702, 1.389, 0.0007, 0.15]
        - time_from_start: 1
          positions: [-1.1, 1.4647, 2.7141, 1.705, -1.702, 1.389, 0.0007, 0.15]
        - time_from_start: 2
          positions: [-1.1, 1.4647, 2.7141, 1.705, -1.702, 1.389, 0.0007, 0.15]
    alive_2:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, 1.4625, 2.7142, 1.7024, -1.7024, 1.3886, 0.0007, 0.15]
        - time_from_start: 1
          positions: [-0.9174, 1.4595, 2.4358, 1.6983, -1.7024, 1.3886, 0, 0.15]
        - time_from_start: 2
          positions: [-1.1001, 1.465, 2.7141, 1.7049, -1.7024, 1.3886, 0.0011, 0.15]
    alive_3:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1001, 1.4629, 2.7142, 1.7024, -1.7028, 1.3882, 0.0011, 0.15]
        - time_from_start: 1
          positions: [-0.9174, 1.4595, 2.4358, 1.6983, -1.7028, 1.3882, 0, 0.15]
        - time_from_start: 2
          positions: [-1.1001, 1.465, 2.7141, 1.7049, -1.7028, 1.3882, 0.0011, 0.15]
    alive_4:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1001, 1.4629, 2.7142, 1.7024, -1.7032, 1.3878, 0.0011, 0.15]
        - time_from_start: 1
          positions: [-1.1, 1.4581, 2.7101, 1.3847, -1.7004, 1.3889, 0, 0.20]
        - time_from_start: 3
          positions: [-1.1, 1.4581, 2.7101, 2.0108, -1.7004, 1.1668, 0, 0.20]
        - time_from_start: 4
          positions: [-1.1001, 1.4629, 2.7142, 1.7024, -1.7032, 1.3878, 0.0011, 0.15]
    alive_5:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1001, 1.461, 2.7143, 1.7002, -1.7036, 1.3875, 0.0011, 0.15]
        - time_from_start: 1.5
          positions: [-0.5521, 1.16, 2.5276, 2.063, -1.7004, 0.6079, 0, 0.1895]
        - time_from_start: 3
          positions: [-1.1001, 1.461, 2.7143, 1.7002, -1.7036, 1.3875, 0.0011, 0.15]
    alive:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, torso_lift_joint]
      points:
        - time_from_start: 0
          positions: [-1.1, 1.4656, 2.7141, 1.7068, -1.7016, 1.3894, 0, 0.1395]
        - time_from_start: 1.5
          positions: [-1.1, 1.1, 2.7141, 1.5, -1.7016, 1.3894, 0, 0.25]
        - time_from_start: 1.75
          positions: [-1.1, 1.1, 2.7141, 1.5, -1.7016, 1.3894, 0, 0.25]
        - time_from_start: 3
          positions: [-1.1, 1.4658, 2.7141, 1.7067, -1.7016, 1.3894, 0.0007, 0.15]
