arm_left_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_left_1_motor
    - arm_left_2_motor
    - arm_left_3_motor
    - arm_left_4_motor
    - arm_left_5_motor
    - arm_left_6_motor
    - arm_left_7_motor

arm_right_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_right_1_motor
    - arm_right_2_motor
    - arm_right_3_motor
    - arm_right_4_motor
    - arm_right_5_motor
    - arm_right_6_motor
    - arm_right_7_motor

# These seem to not be used
#hand_left_current_limit_controller:
  #type: "pal_ros_controllers/CurrentLimitController"
  #actuators:
    #- hand_left_thumb_motor
    #- hand_left_index_motor
    #- hand_left_mrl_motor

#hand_right_current_limit_controller:
  #type: "pal_ros_controllers/CurrentLimitController"
  #actuators:
    #- hand_right_thumb_motor
    #- hand_right_index_motor
    #- hand_right_mrl_motor

# TODO add other base
wheels_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - wheel_front_left_motor
    - wheel_rear_left_motor
    - wheel_front_right_motor
    - wheel_rear_right_motor
