hand_right_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - hand_right_thumb_joint
      - hand_right_index_joint
      - hand_right_mrl_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.75
      hand_right_thumb_joint:
        goal: &hand_goal_pos_constraint 0.3
      hand_right_index_joint:
        goal: 0.6
      hand_right_mrl_joint:
        goal: *hand_goal_pos_constraint
      stop_trajectory_duration: 0.0
